schema_version = "1.0.0"

id = "idtech2_bsp_importer"
version = "2.0.0"
name = "idTech 2 BSP Importer"
tagline = "Import idTech 2 (Quake II, Anachronox, etc...) maps (BSP format) into Blender "
maintainer = "GeneralProtectionFault"
type = "add-on"

blender_version_min = "4.2.0"
location = "File > Import > idTech 2 [Quake II/Anachronox] (.BSP)"

website = "https://github.com/GeneralProtectionFault/idTech-2-BSP-Blender-Importer"


license = [
  "GPL-3.0-or-later",
]

wheels = [
  "./wheels/pillow-12.0.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-12.0.0-cp311-cp311-macosx_10_10_x86_64.whl"
]
